<?php
$this->placeholder('TitreHaut')->set($this->oActi->getNom().$this->translate("page.admin.titre.inscriptions.listings"));
// $this->headScript()->appendFile(SCRIPTS_PATH.'/projet/forms/multiInput.js');
$this->headLink()->appendStylesheet(STYLES_PATH.'/Listings.css');
// $this->headScript()->appendFile(SCRIPTS_PATH.'/forms/filRouge.js');

// echo new Projet_Xml('div', array('class' => 'howto'.CSS_LAYOUT_TEXT), $this->message);
// echo $this->form;
echo $this->liste;

